# Generated by Django 4.0.3 on 2022-03-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_bio_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='software dev'),
            preserve_default=False,
        ),
    ]
