# Generated by Django 4.0.3 on 2022-03-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_avatar_profile_image_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/Avatar.png', upload_to='images'),
        ),
    ]
